### ISSUE TITLE
Can we get AI to write reviews in other languages?

### ISSUE THREAD

**Issue by antop-dev** [truongnh1992/gemini-ai-code-reviewer#44]
Thank you for the Actions you created.

For example, you can write a review with the `LANG` settings as shown below!

```yaml
      - uses: truongnh1992/gemini-ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: gemini-1.5-pro-002 # Optional, default is `gemini-1.5-flash-002`
          EXCLUDE: "*.md,*.txt,package-lock.json,*.yml,*.yaml"
          LANG: "Korean" # here
```
